### ISSUE TITLE
报错啊

### ISSUE THREAD

**Issue by ioojcn** [GilHogan/JDTreasureGrabber#1]
店 开始抢购 后 新窗口会弹出 ""系统繁忙，请稍后再试！""

是什么原因呢
![微信截图_20230828103518](https://github.com/GilHogan/JDTreasureGrabber/assets/4147762/e5f55851-48fa-444c-88ad-b4a8f6ba2fd3)

**Comment by GilHogan** [comment]
@ioojcn 第一次进入正在进行抢购的商品页面时，应用后台会模拟点击“立即出价”按钮出价1元，并且会拦截这次出价请求，从而获取到后续自动出价时要用到的Cookie授权信息。这里的错误弹窗提示可能是和出价1元有关，因为最低出价是2元。

**Comment by ioojcn** [comment]
明白了.获取COOKIE呗.无视就好啦
