### ISSUE TITLE
您好，最近京东好像改规则了，出不了价了

### ISSUE THREAD

**Issue by dhap5** [GilHogan/JDTreasureGrabber#14]
您好，最近京东好像改规则了，出不了价了，麻烦帮忙看看是不是可以修复下！

**Comment by GilHogan** [comment]
您用的哪个版本啊

**Comment by dhap5** [comment]
[v0.4.0](https://github.com/GilHogan/JDTreasureGrabber/releases/tag/v0.4.0)

**Comment by dhap5** [comment]
> 您用的哪个版本啊

[v0.4.0](https://github.com/GilHogan/JDTreasureGrabber/releases/tag/v0.4.0)

**Comment by GilHogan** [comment]
auction.detail参数是用的curl吗? 应用主界面按 Ctrl + Shift +I 打开调试界面看一下日志呢。我这边试了是能出价的啊

**Comment by RichFun8023** [comment]
系统繁忙，请稍后再试！
用google chrome出价 就提示系统繁忙
用360极速就可以出价成功

**Comment by RichFun8023** [comment]
getBatchInfo get end NowPrice =  null , CurrentTime =  1726749619883 , EndTime =  1726749620000 , CurrentTime format =  2024-09-19 20:40:1919 , EndTime format =  2024-09-19 20:40:2020 , CurrentBidder =  null , BidderNickName =  *** , offsetTime =  132
App.vue:50 4444毫秒后出价:2元，当前时间：1726749616120, 上一次请求竞价信息后的剩余时间：117
App.vue:50 1726749616120:出价2
App.vue:50 出价：2元
App.vue:50 postOfferPrice start 出价 =  2  , 当前时间： 2024-09-19 20:40:1616 1726749616121
App.vue:50 postOfferPrice end 出价: 2 , 当前时间： 2024-09-19 20:40:1616 1726749616232  , 结果:
App.vue:50 ["postOfferPrice error: ","Unexpected end of JSON input"]
App.vue:50 getBatchInfo get end NowPrice =  null , CurrentTime =  1726749621231 , EndTime =  1726749620000 , CurrentTime format =  2024-09-19 20:40:2121 , EndTime format =  2024-09-19 20:40:2020 , CurrentBidder =  null , BidderNickName =  *** , offsetTime =  118
App.vue:50 sendNotice msg =  夺宝已结束-已出价
这是调试信息

**Comment by GilHogan** [comment]
> getBatchInfo get end NowPrice = null , CurrentTime = 1726749619883 , EndTime = 1726749620000 , CurrentTime format = 2024-09-19 20:40:1919 , EndTime format = 2024-09-19 20:40:2020 , CurrentBidder = null , BidderNickName = *** , offsetTime = 132 App.vue:50 4444毫秒后出价:2元，当前时间：1726749616120, 上一次请求竞价信息后的剩余时间：117 App.vue:50 1726749616120:出价2 App.vue:50 出价：2元 App.vue:50 postOfferPrice start 出价 = 2 , 当前时间： 2024-09-19 20:40:1616 1726749616121 App.vue:50 postOfferPrice end 出价: 2 , 当前时间： 2024-09-19 20:40:1616 1726749616232 , 结果: App.vue:50 ["postOfferPrice error: ","Unexpected end of JSON input"] App.vue:50 getBatchInfo get end NowPrice = null , CurrentTime = 1726749621231 , EndTime = 1726749620000 , CurrentTime format = 2024-09-19 20:40:2121 , EndTime format = 2024-09-19 20:40:2020 , CurrentBidder = null , BidderNickName = *** , offsetTime = 118 App.vue:50 sendNotice msg = 夺宝已结束-已出价 这是调试信息

选择的是后台出价吗

**Comment by RichFun8023** [comment]
商品抢购已接近尾声，开始倒计时抢购处理  2024-09-19 20:50:04
App.vue:50 getBatchInfo get end NowPrice =  24 , CurrentTime =  1726750208325 , EndTime =  1726750213000 , CurrentTime format =  2024-09-19 20:50:088 , EndTime format =  2024-09-19 20:50:1313 , CurrentBidder =  jd***jC , BidderNickName =  jd***e5 , offsetTime =  146
App.vue:50 当前价格：24  , 最高价格：30  , 当前时间：2024-09-19 20:50:044
App.vue:50 剩余抢购时间 毫秒：4675  , 秒：4
App.vue:50 当前出价人：jd***jC  ,抢购用户账户名：
App.vue:50 4439毫秒后开始出价
App.vue:50 start last update batchInfo.
App.vue:50 getBatchInfo get end NowPrice =  24 , CurrentTime =  1726750212845 , EndTime =  1726750213000 , CurrentTime format =  2024-09-19 20:50:1212 , EndTime format =  2024-09-19 20:50:1313 , CurrentBidder =  jd***jC , BidderNickName =  jd***e5 , offsetTime =  107
App.vue:50 4439毫秒后出价:25元，当前时间：1726750209063, 上一次请求竞价信息后的剩余时间：155
App.vue:50 1726750209063:出价25
App.vue:50 出价：25元
App.vue:50 postOfferPrice start 出价 =  25  , 当前时间： 2024-09-19 20:50:099 1726750209064
App.vue:50 postOfferPrice end 出价: 25 , 当前时间： 2024-09-19 20:50:099 1726750209188  , 结果:
App.vue:50 ["postOfferPrice error: ","Unexpected end of JSON input"]
App.vue:50 getBatchInfo get end NowPrice =  24 , CurrentTime =  1726750214268 , EndTime =  1726750213000 , CurrentTime format =  2024-09-19 20:50:1414 , EndTime format =  2024-09-19 20:50:1313 , CurrentBidder =  jd***jC , BidderNickName =  jd***e5 , offsetTime =  122
App.vue:50 sendNotice msg =  夺宝已结束-已出价

这个没有勾选后台出价 也不行
即使现在我用google Chrome前台手动点出价 就会提示 系统繁忙，请稍后再试！

**Comment by GilHogan** [comment]
请更新到[v0.4.1](https://github.com/GilHogan/JDTreasureGrabber/releases/tag/v0.4.1)再试试。注意：该版本仅支持点击页面按钮出价的方式，最小化浏览器或离开商品页面不会进行后续的出价 :-)
