### ISSUE TITLE
获取最后一次出价的时间能自定义设置嘛？他现在怎么提前4秒多获取

### ISSUE THREAD

**Issue by RichFun8023** [GilHogan/JDTreasureGrabber#17]
提前太多了。完全抢不到
![IMG_5650](https://github.com/user-attachments/assets/3b0f9191-c9e0-4a3a-89d2-0e7527675b60)

**Comment by GilHogan** [comment]
并没有提前4秒获取，抢不到大概率只是有人出更高的价格了。最后出价倒数时间就是约等于最后一次获取价格的时间。

**Comment by RichFun8023** [comment]
抢了一天同款，一直都是提示出价比别人低:
大佬这个工作日志最后一次获取价格是什么时候
头疼。抢了一天  没抢到

**Comment by GilHogan** [comment]
试试一口价的出价方式，最后一次获取价格的倒数时间是 设置的出价倒数时间+155 毫秒

**Comment by RichFun8023** [comment]
可以自定义这个毫秒速嘛 发哪里，

**Comment by RichFun8023** [comment]
可以自定义最后一次获取价格的毫秒速嘛 大佬

**Comment by GilHogan** [comment]
> 可以自定义最后一次获取价格的毫秒速嘛 大佬

就是主界面的“最后出价倒数时间”这里设置的啊
