### ISSUE TITLE
开始抢购后总提示“系统忙，请稍后再试”

### ISSUE THREAD

**Issue by TobyCTL** [GilHogan/JDTreasureGrabber#2]
![image](https://github.com/GilHogan/JDTreasureGrabber/assets/20085099/e30a6a1f-1a3e-43df-97bb-30bf9f914f79)
您好，用WIN平台ZIP包程序，开始抢购后总提示“系统忙，请稍后再试”，请问是啥问题呢？

**Comment by GilHogan** [comment]
这是正常的，参见 https://github.com/GilHogan/JDTreasureGrabber/issues/1#issuecomment-1694940594
