### ISSUE TITLE
你好，你的项目对我很有用，但是这里有个报错，可以看下吗

### ISSUE THREAD

**Issue by nonepage** [GilHogan/JDTreasureGrabber#4]
你好，你的软件很好用，帮助我拍下了我急需的商品，但是我现在想要只看到9成新的商品，想改一改您的项目，但是在构建的时候出现了一个错误：
(node:26776) electron: Failed to load URL: file:///C:/Users/JDTreasureGrabber-master/pages/index.html with error: ERR_FILE_NOT_FOUND
好像是有一个index.html没有，可以帮助我解决这个问题吗，十分感谢

**Comment by GilHogan** [comment]
你好，能否参考这个issues尝试解决 https://github.com/electron/electron/issues/1769

**Comment by nonepage** [comment]
大佬，好像是这个文件没有哇，不是没有引用吧

**Comment by nonepage** [comment]
![image](https://github.com/GilHogan/JDTreasureGrabber/assets/45900333/1ea183f3-04f3-4799-81f8-382adca54fe0)

**Comment by GilHogan** [comment]
> ![image](https://user-images.githubusercontent.com/45900333/279894330-1ea183f3-04f3-4799-81f8-382adca54fe0.png)

需要先执行这个命令构建一下：npm run build

**Comment by nonepage** [comment]
非常感谢！已解决
